# Generated by Django 4.2.11 on 2025-05-13 20:49

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("uid", models.CharField(max_length=255, unique=True)),
                (
                    "alias",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("notification_distance", models.IntegerField(default=500)),
                ("privacy", models.CharField(default="publico", max_length=50)),
                ("role", models.CharField(default="user", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("necesidades", models.JSONField(default=dict)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "kudos_app_user",
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("type", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("expiration", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("activa", "Activa"), ("expirada", "Expirada")],
                        default="activa",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="AutomationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("automation_level", models.IntegerField(default=10)),
                ("support_automation", models.BooleanField(default=True)),
                ("support_threshold", models.FloatField(default=0.5)),
                ("moderation_automation", models.BooleanField(default=True)),
                ("moderation_threshold", models.FloatField(default=0.2)),
                (
                    "moderation_review_frequency",
                    models.CharField(
                        choices=[("daily", "Diaria"), ("weekly", "Semanal")],
                        default="daily",
                        max_length=50,
                    ),
                ),
                (
                    "content_creation_frequency",
                    models.CharField(
                        choices=[("daily", "Diaria"), ("weekly", "Semanal")],
                        default="daily",
                        max_length=50,
                    ),
                ),
                ("content_creation_limit", models.IntegerField(default=100)),
                ("storage_network", models.CharField(default="none", max_length=50)),
                ("storage_limit_per_user", models.IntegerField(default=1000)),
                ("processing_network", models.CharField(default="none", max_length=50)),
                ("max_task_cost", models.FloatField(default=1.0)),
                ("webgpu_enabled", models.BooleanField(default=True)),
                ("compression_level", models.IntegerField(default=5)),
                ("energy_renewable_percentage", models.IntegerField(default=50)),
                ("energy_reduction_goal", models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name="Capsule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=100, unique=True)),
                ("contenido", models.TextField()),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("modo", models.CharField(default="publico", max_length=50)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("privacy", models.CharField(default="publico", max_length=50)),
                ("time_scale", models.CharField(default="dia", max_length=50)),
                ("price", models.FloatField(default=0.0)),
                ("temas", models.JSONField(default=list)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("rol", models.CharField(max_length=20)),
                ("theme", models.CharField(max_length=50)),
                ("culture", models.CharField(max_length=50)),
                ("nationality", models.CharField(max_length=50)),
                ("religion", models.CharField(blank=True, max_length=50, null=True)),
                ("imagen_ninos", models.URLField()),
                ("imagen_adultos", models.URLField()),
                ("audio_guia", models.URLField(blank=True, null=True)),
                ("modelo_ar", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExternalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("source", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("content", models.JSONField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="ImprovementProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                ("estimated_benefit", models.FloatField()),
                ("estimated_cost", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("validada", "Validada"),
                            ("en_progreso", "En Progreso"),
                            ("completada", "Completada"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("description", models.TextField()),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("attribution", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="SettingsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.IntegerField(blank=True, null=True)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="WisdomSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "subthemes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("theme", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                ("attribution", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="VirtualOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("operation_type", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.FloatField()),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("city", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("content_type", models.CharField(max_length=50)),
                ("content_id", models.CharField(max_length=50)),
                ("amount", models.FloatField()),
                ("commission", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("theme", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("price", models.FloatField(default=0.0)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                ("attribution", models.TextField(blank=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="social_spaces", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("contenido", models.TextField()),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("modo", models.CharField(default="publico", max_length=20)),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("solo_yo", "Solo Yo"),
                            ("familia", "Familia"),
                            ("amigos", "Amigos"),
                            ("publico", "Público"),
                        ],
                        default="publico",
                        max_length=20,
                    ),
                ),
                ("time_scale", models.CharField(default="dia", max_length=20)),
                ("distance", models.FloatField(default=0.0)),
                ("altitude_gain", models.FloatField(default=0.0)),
                ("sport_type", models.CharField(default="other", max_length=20)),
                ("price", models.FloatField(default=0.0)),
                (
                    "temas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        default=list,
                        size=None,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("attribution", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PromotionSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("category", models.CharField(max_length=50)),
                ("subcategory", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("price", models.FloatField(default=0.0)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                ("attribution", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=20)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("No leída", "No leída"),
                            ("Leída", "Leída"),
                            ("Procesada", "Procesada"),
                        ],
                        default="No leída",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                ("sent", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="kudos_app.capsule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(default="Anónimo", max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                        ],
                        max_length=1,
                    ),
                ),
                ("comment", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="kudos_app.capsule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_issued",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("certificate_file", models.FileField(upload_to="certificates/")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kudos_app.capsule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "date_awarded",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_level", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uid", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField()),
                (
                    "ubicacion",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("parameters", models.JSONField(default=dict)),
                ("variables", models.JSONField(default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
