# Generated by Django 4.2.21 on 2025-05-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kudos_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AutomationConfig",
        ),
        migrations.AddField(
            model_name="capsule",
            name="variables",
            field=models.JSONField(default=dict),
        ),
    ]
