# Generated by Django 5.0.14 on 2026-05-04 19:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ej: Filósofo estoico romano",
                        max_length=200,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        help_text="Tema en el que es experto", max_length=80
                    ),
                ),
                ("icon", models.CharField(default="🏛", max_length=10)),
                ("color", models.CharField(default="#1E3A8A", max_length=10)),
                ("intro", models.TextField(help_text="Cómo se presenta al usuario")),
                (
                    "voice_style",
                    models.TextField(help_text="Tono y estilo de respuesta"),
                ),
                (
                    "typical_quotes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Frases típicas del personaje",
                    ),
                ),
                (
                    "suggested_for",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de departamentos/temas sugeridos",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SettingsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "uid",
                    models.CharField(
                        help_text="Identificador único", max_length=255, unique=True
                    ),
                ),
                ("alias", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("avatar", models.URLField(blank=True, default="")),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("notification_distance", models.IntegerField(default=500)),
                ("privacy", models.CharField(default="publico", max_length=50)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("founder", "Fundador"),
                            ("admin", "Administrador"),
                            ("user", "Usuario"),
                            ("guest", "Invitado"),
                        ],
                        default="user",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("necesidades", models.JSONField(blank=True, default=dict)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("experience_points", models.IntegerField(default=0)),
                ("level", models.IntegerField(default=1)),
                ("dark_mode", models.BooleanField(default=False)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="kudos_user_groups", to="auth.group"
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="kudos_user_permissions",
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                ("descripcion", models.TextField()),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("variables", models.JSONField(blank=True, default=dict)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Actividades",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🏆", max_length=10)),
                (
                    "date_awarded",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_awarded"],
            },
        ),
        migrations.CreateModel(
            name="Capsule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                ("titulo", models.CharField(blank=True, default="", max_length=200)),
                ("contenido", models.TextField()),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("lugar", models.CharField(blank=True, default="", max_length=255)),
                (
                    "modo",
                    models.CharField(
                        choices=[
                            ("historico", "Histórico"),
                            ("ciudadano", "Ciudadano"),
                            ("sabiduria", "Sabiduría"),
                            ("arte", "Arte"),
                            ("espiritual", "Espiritual"),
                            ("personal", "Personal"),
                            ("comercial", "Comercial"),
                        ],
                        default="historico",
                        max_length=50,
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "privacy",
                    models.CharField(
                        choices=[
                            ("publico", "Público"),
                            ("privado", "Privado"),
                            ("amigos", "Solo amigos"),
                        ],
                        default="publico",
                        max_length=50,
                    ),
                ),
                ("time_scale", models.CharField(default="dia", max_length=50)),
                ("temas", models.JSONField(blank=True, default=list)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("variables", models.JSONField(blank=True, default=dict)),
                ("image", models.CharField(blank=True, max_length=500, null=True)),
                ("audio", models.CharField(blank=True, max_length=500, null=True)),
                ("video", models.CharField(blank=True, max_length=500, null=True)),
                ("likes", models.IntegerField(default=0)),
                ("views", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("source", models.CharField(blank=True, default="", max_length=100)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capsules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Cápsula",
                "verbose_name_plural": "Cápsulas",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_issued",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "certificate_file",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="kudos_app.capsule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("sport", models.CharField(default="general", max_length=50)),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_virtual", models.BooleanField(default=True)),
                ("entry_price", models.FloatField(default=0.0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="CryptoWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    models.CharField(help_text="BTC, ETH, SOL...", max_length=20),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Tu tesis sobre esta cripto"
                    ),
                ),
                (
                    "target_buy_eur",
                    models.FloatField(
                        blank=True, help_text="Precio objetivo de compra", null=True
                    ),
                ),
                (
                    "target_sell_eur",
                    models.FloatField(
                        blank=True, help_text="Precio objetivo de venta", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_watches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["symbol"],
                "unique_together": {("user", "symbol")},
            },
        ),
        migrations.CreateModel(
            name="CryptoOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("buy", "🟢 Compra"),
                            ("sell", "🔴 Venta"),
                            ("hold", "🟡 Hold"),
                            ("note", "📝 Nota"),
                        ],
                        default="note",
                        max_length=10,
                    ),
                ),
                ("symbol", models.CharField(default="", max_length=20)),
                (
                    "amount",
                    models.FloatField(default=0, help_text="Cantidad de unidades"),
                ),
                (
                    "price_eur",
                    models.FloatField(default=0, help_text="Precio por unidad en EUR"),
                ),
                ("total_eur", models.FloatField(default=0)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "rule_followed",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="¿Qué regla personal seguiste o rompiste?",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kudos_app.cryptowatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(default="🏛", max_length=10)),
                ("mission", models.TextField(default="")),
                ("description", models.TextField(default="")),
                (
                    "head_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cuando aún no hay persona asignada",
                        max_length=120,
                    ),
                ),
                ("color", models.CharField(default="#1E3A8A", max_length=10)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "head_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leading_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subdepartments",
                        to="kudos_app.department",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("income", "Ingreso"),
                            ("cost", "Coste"),
                            ("investment", "Inversión"),
                        ],
                        default="cost",
                        max_length=15,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="Ej: Hosting, Marketing, Salarios, Suscripciones",
                        max_length=80,
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "amount_eur",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, help_text="Mensual"),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_lines",
                        to="kudos_app.department",
                    ),
                ),
            ],
            options={
                "ordering": ["year", "type", "category"],
            },
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("strategic", "Estratégico (años)"),
                            ("annual", "Anual"),
                            ("quarterly", "Trimestral"),
                            ("monthly", "Mensual"),
                        ],
                        default="quarterly",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("idea", "Idea"),
                            ("planned", "Planificado"),
                            ("in_progress", "En curso"),
                            ("done", "Conseguido"),
                            ("blocked", "Bloqueado"),
                            ("dropped", "Descartado"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0, help_text="0-100")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="vault, connect, mind",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(default=2, help_text="1=alta, 2=media, 3=baja"),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="goals",
                        to="kudos_app.department",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "end_date", "-created"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salud", "💪 Salud"),
                            ("aprendizaje", "📚 Aprendizaje"),
                            ("espiritual", "🧘 Espiritual"),
                            ("productividad", "⚡ Productividad"),
                            ("finanzas", "💰 Finanzas"),
                            ("relaciones", "❤ Relaciones"),
                        ],
                        default="salud",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(default="✓", max_length=10)),
                (
                    "target_per_week",
                    models.IntegerField(default=7, help_text="Veces por semana"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("streak_days", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("morning", "🌅 Mañana - Intención"),
                            ("evening", "🌙 Noche - Examen"),
                            ("reflection", "🤔 Reflexión libre"),
                            ("decision", "⚖ Decisión importante"),
                            ("lesson", "📖 Lección aprendida"),
                        ],
                        default="morning",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("content", models.TextField()),
                ("mood", models.IntegerField(default=5, help_text="1-10")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_private", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Identificador interno: ej. growth.dau, content.total_capsules",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ej: cápsulas, usuarios, %, €, K",
                        max_length=20,
                    ),
                ),
                ("target_value", models.FloatField(default=0)),
                ("current_value", models.FloatField(default=0)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_higher_better", models.BooleanField(default=True)),
                (
                    "formula",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cómo se calcula (informativo)",
                        max_length=200,
                    ),
                ),
                ("icon", models.CharField(default="📊", max_length=10)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kpis",
                        to="kudos_app.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department__order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LearningItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("libro", "📚 Libro"),
                            ("curso", "🎓 Curso"),
                            ("video", "🎥 Vídeo / charla"),
                            ("paper", "📄 Paper / artículo"),
                            ("podcast", "🎙 Podcast"),
                            ("practica", "💪 Práctica"),
                        ],
                        default="libro",
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(blank=True, default="", max_length=200)),
                ("url", models.URLField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("por_leer", "Por leer"),
                            ("en_curso", "En curso"),
                            ("completado", "Completado"),
                            ("abandonado", "Abandonado"),
                        ],
                        default="por_leer",
                        max_length=15,
                    ),
                ),
                ("progress_percent", models.IntegerField(default=0)),
                (
                    "notes",
                    models.TextField(
                        blank=True, default="", help_text="Notas y aprendizajes"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True, help_text="1-5 estrellas", null=True
                    ),
                ),
                ("started", models.DateField(blank=True, null=True)),
                ("finished", models.DateField(blank=True, null=True)),
                (
                    "priority",
                    models.IntegerField(default=2, help_text="1=alta, 2=media, 3=baja"),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "-created"],
            },
        ),
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        choices=[
                            ("feliz", "😊 Feliz"),
                            ("neutro", "😐 Neutro"),
                            ("triste", "😔 Triste"),
                            ("ansioso", "😰 Ansioso"),
                            ("motivado", "🚀 Motivado"),
                            ("cansado", "😴 Cansado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mood_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(default="info", max_length=50)),
                ("message", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("baja", "Baja"),
                            ("media", "Media"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("read", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Proposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("themes", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("debate", "En debate"),
                            ("aprobada", "Aprobada"),
                            ("rechazada", "Rechazada"),
                            ("ejecutada", "Ejecutada"),
                        ],
                        default="debate",
                        max_length=20,
                    ),
                ),
                ("votes_for", models.IntegerField(default=0)),
                ("votes_against", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("comment", models.TextField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="kudos_app.capsule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("summary", models.CharField(blank=True, default="", max_length=255)),
                (
                    "responsibilities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de responsabilidades clave",
                    ),
                ),
                (
                    "holder_label",
                    models.CharField(blank=True, default="Vacante", max_length=120),
                ),
                ("is_executive", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="kudos_app.department",
                    ),
                ),
                (
                    "holder_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="held_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["department__order", "order", "title"],
            },
        ),
        migrations.CreateModel(
            name="SocialSpace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="🌐", max_length=10)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_spaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="StrategicDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("manifest", "Manifiesto"),
                            ("strategic", "Plan estratégico"),
                            ("tactical", "Plan táctico"),
                            ("financial", "Plan financiero"),
                            ("legal", "Documento legal"),
                            ("communication", "Comunicación / Marketing"),
                            ("operational", "Operativo"),
                            ("personal", "Personal del fundador"),
                        ],
                        default="strategic",
                        max_length=20,
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, default="", max_length=300)),
                ("body", models.TextField(default="")),
                ("version", models.CharField(default="1.0", max_length=10)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="kudos_app.department",
                    ),
                ),
            ],
            options={
                "ordering": ["department__order", "kind", "title"],
            },
        ),
        migrations.CreateModel(
            name="VirtualOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.CharField(default=uuid.uuid4, max_length=100, unique=True),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("venta", "Venta"),
                            ("compra", "Compra"),
                            ("intercambio", "Intercambio"),
                            ("subasta", "Subasta"),
                        ],
                        default="venta",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("price", models.FloatField(default=0.0)),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("variables", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="HabitLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="kudos_app.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("habit", "date")},
            },
        ),
        migrations.CreateModel(
            name="HealthMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("sueño_horas", "😴 Sueño (horas)"),
                            ("ejercicio_min", "🏃 Ejercicio (min)"),
                            ("peso_kg", "⚖ Peso (kg)"),
                            ("agua_litros", "💧 Agua (L)"),
                            ("lectura_min", "📖 Lectura (min)"),
                            ("meditacion_min", "🧘 Meditación (min)"),
                            ("pasos", "👣 Pasos"),
                            ("animo", "😊 Ánimo (1-10)"),
                            ("energia", "⚡ Energía (1-10)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.FloatField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True, default="")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "metric"],
                "unique_together": {("user", "metric", "date")},
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "capsule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_by",
                        to="kudos_app.capsule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("capsule", "user")},
            },
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_favor", models.BooleanField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="kudos_app.proposal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("proposal", "user")},
            },
        ),
    ]
